// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Award Award.xlsx#Award
type Award struct {
	CardID int32 `json:"CardID"` // 卡牌編號
	Group int32 `json:"Group"` // 抽獎群組編號
	ID int32 `json:"ID"` // 流水號
	Weight int32 `json:"Weight"` // 權重
}

// AwardReader Award.xlsx#Award
type AwardReader struct {
	Data map[int32]*Award // 資料列表
}

// FileName 取得檔名物件
func (this *AwardReader) FileName() FileName {
	return NewFileName("award", ".json")
}

// FromData 讀取資料
func (this *AwardReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[int32]*Award{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[int32]*Award{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [award : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *AwardReader) Clear() {
	this.Data = map[int32]*Award{}
}

// Get 取得資料
func (this *AwardReader) Get(key int32) *Award {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *AwardReader) Keys() (result []int32) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *AwardReader) Values() (result []*Award) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *AwardReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *AwardReader) Count() int {
	return len(this.Data)
}
