// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Card Card.xlsx#Card
type Card struct {
	Cost int32 `json:"Cost"` // 出牌費用
	ExtraRunMax int32 `json:"ExtraRunMax"` // 額外發動次數上限
	ExtraRunMin int32 `json:"ExtraRunMin"` // 額外發動次數下限
	Group int32 `json:"Group"` // 卡牌群組編號
	ID int32 `json:"ID"` // 卡牌編號
	Keep bool `json:"Keep"` // 不棄卡牌
	Name string `json:"Name"` // 名稱
	PlayExile bool `json:"PlayExile"` // 出牌後流放
	Seal bool `json:"Seal"` // 封印卡牌
	SkillID int32 `json:"SkillID"` // 技能編號
	UnplayExile bool `json:"UnplayExile"` // 未出牌流放
}

// CardReader Card.xlsx#Card
type CardReader struct {
	Data map[int32]*Card // 資料列表
}

// FileName 取得檔名物件
func (this *CardReader) FileName() FileName {
	return NewFileName("card", ".json")
}

// FromData 讀取資料
func (this *CardReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[int32]*Card{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[int32]*Card{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [card : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *CardReader) Clear() {
	this.Data = map[int32]*Card{}
}

// Get 取得資料
func (this *CardReader) Get(key int32) *Card {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *CardReader) Keys() (result []int32) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *CardReader) Values() (result []*Card) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *CardReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *CardReader) Count() int {
	return len(this.Data)
}
