// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Effect Effect.xlsx#Effect
type Effect struct {
	CommandEnd string `json:"CommandEnd"` // 結束命令
	CommandImmed string `json:"CommandImmed"` // 立即命令
	CommandStart string `json:"CommandStart"` // 啟動命令
	CommandTrigger string `json:"CommandTrigger"` // 觸發命令
	Group int32 `json:"Group"` // 效果群組編號
	ID int32 `json:"ID"` // 效果編號
	Kind int32 `json:"Kind"` // 效果類型
	Name string `json:"Name"` // 名稱
	RunOrder int32 `json:"RunOrder"` // 作用順序
	RunRound int32 `json:"RunRound"` // 作用回合
	Stack int32 `json:"Stack"` // 堆疊層數
	StackMax int32 `json:"StackMax"` // 堆疊上限
	StackTime int32 `json:"StackTime"` // 堆疊時間
	TargetCount int32 `json:"TargetCount"` // 目標數量
	TargetKind int32 `json:"TargetKind"` // 目標類型
	TriggerAfter int32 `json:"TriggerAfter"` // 觸發後行為
	TriggerCond string `json:"TriggerCond"` // 觸發條件
	TriggerCount string `json:"TriggerCount"` // 觸發次數
	TriggerKind int32 `json:"TriggerKind"` // 觸發時機
}

// EffectReader Effect.xlsx#Effect
type EffectReader struct {
	Data map[int32]*Effect // 資料列表
}

// FileName 取得檔名物件
func (this *EffectReader) FileName() FileName {
	return NewFileName("effect", ".json")
}

// FromData 讀取資料
func (this *EffectReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[int32]*Effect{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[int32]*Effect{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [effect : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *EffectReader) Clear() {
	this.Data = map[int32]*Effect{}
}

// Get 取得資料
func (this *EffectReader) Get(key int32) *Effect {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *EffectReader) Keys() (result []int32) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *EffectReader) Values() (result []*Effect) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *EffectReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *EffectReader) Count() int {
	return len(this.Data)
}
