// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Guest Guest.xlsx#Guest
type Guest struct {
	Calm int32 `json:"Calm"` // 耐心值
	CalmSeal bool `json:"CalmSeal"` // 封印耐心技能
	CalmSkillID []string `json:"CalmSkillID"` // 耐心技能列表
	ID int32 `json:"ID"` // 顧客編號
	Morale int32 `json:"Morale"` // 士氣值
	MoraleMax int32 `json:"MoraleMax"` // 士氣值上限
	Name string `json:"Name"` // 名稱
	SateMax int32 `json:"SateMax"` // 飽食值離場線
	SateSeal bool `json:"SateSeal"` // 封印飽食技能
	SateSkillID []string `json:"SateSkillID"` // 飽食技能列表
	Score int32 `json:"Score"` // 滿意值
	ScoreMax int32 `json:"ScoreMax"` // 滿意值上限
}

// GuestReader Guest.xlsx#Guest
type GuestReader struct {
	Data map[int32]*Guest // 資料列表
}

// FileName 取得檔名物件
func (this *GuestReader) FileName() FileName {
	return NewFileName("guest", ".json")
}

// FromData 讀取資料
func (this *GuestReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[int32]*Guest{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[int32]*Guest{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [guest : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *GuestReader) Clear() {
	this.Data = map[int32]*Guest{}
}

// Get 取得資料
func (this *GuestReader) Get(key int32) *Guest {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *GuestReader) Keys() (result []int32) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *GuestReader) Values() (result []*Guest) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *GuestReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *GuestReader) Count() int {
	return len(this.Data)
}
