// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Seat Seat.xlsx#Seat
type Seat struct {
	ID int32 `json:"ID"` // 座位編號
	NearSeatID []int32 `json:"NearSeatID"` // 鄰桌座位編號列表
	SameSeatID []int32 `json:"SameSeatID"` // 同桌座位編號列表
	TableID int32 `json:"TableID"` // 桌次編號
}

// SeatReader Seat.xlsx#Seat
type SeatReader struct {
	Data map[int32]*Seat // 資料列表
}

// FileName 取得檔名物件
func (this *SeatReader) FileName() FileName {
	return NewFileName("seat", ".json")
}

// FromData 讀取資料
func (this *SeatReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[int32]*Seat{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[int32]*Seat{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [seat : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *SeatReader) Clear() {
	this.Data = map[int32]*Seat{}
}

// Get 取得資料
func (this *SeatReader) Get(key int32) *Seat {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *SeatReader) Keys() (result []int32) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *SeatReader) Values() (result []*Seat) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *SeatReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *SeatReader) Count() int {
	return len(this.Data)
}
