// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Setting Setting.xlsx#Setting
type Setting struct {
	CodeName string `json:"CodeName"` // 程式名稱
	CodeNote string `json:"CodeNote"` // 程式註解
	ID string `json:"ID"` // 設定名稱
	Value []string `json:"Value"` // 設定值
}

// SettingReader Setting.xlsx#Setting
type SettingReader struct {
	Data map[string]*Setting // 資料列表
}

// FileName 取得檔名物件
func (this *SettingReader) FileName() FileName {
	return NewFileName("setting", ".json")
}

// FromData 讀取資料
func (this *SettingReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[string]*Setting{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[string]*Setting{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [setting : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *SettingReader) Clear() {
	this.Data = map[string]*Setting{}
}

// Get 取得資料
func (this *SettingReader) Get(key string) *Setting {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *SettingReader) Keys() (result []string) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *SettingReader) Values() (result []*Setting) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *SettingReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *SettingReader) Count() int {
	return len(this.Data)
}
