// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"sync"
	"sync/atomic"
)

// NewSheeter 建立表格資料
func NewSheeter(loader Loader) *Sheeter {
	sheeter := &Sheeter{}
	sheeter.loader = loader
	sheeter.progress = NewProgress()
	return sheeter
}

// Sheeter 表格資料
type Sheeter struct {
	loader Loader // 裝載器物件
	progress *Progress // 進度物件
	Award AwardReader // Award.xlsx#Award
	Card CardReader // Card.xlsx#Card
	Effect EffectReader // Effect.xlsx#Effect
	Guest GuestReader // Guest.xlsx#Guest
	Seat SeatReader // Seat.xlsx#Seat
	Setting SettingReader // Setting.xlsx#Setting
	Skill SkillReader // Skill.xlsx#Skill
	Stage StageReader // Stage.xlsx#Stage
}

// FromData 讀取資料處理
func (this *Sheeter) FromData() bool {
	this.progress.Reset()

	if this.loader == nil {
		return false
	} // if

	waitGroup := sync.WaitGroup{}
	result := atomic.Bool{}
	result.Store(true)

	for _, itor := range []Reader{
		&this.Award,
		&this.Card,
		&this.Effect,
		&this.Guest,
		&this.Seat,
		&this.Setting,
		&this.Skill,
		&this.Stage,
	} {
		waitGroup.Go(func() {
			filename := itor.FileName()
			data := this.loader.Load(filename)

			if len(data) == 0 {
				return
			} // if

			if err := itor.FromData(data, true, this.progress); err != nil {
				this.loader.Error(filename.File(), err)
				result.Store(false)
			} // if
		})
	} // for

	waitGroup.Wait()
	this.progress.Complete()
	return result.Load()
}

// Clear 清除資料
func (this *Sheeter) Clear() {
	this.progress.Reset()
	this.Award.Clear()
	this.Card.Clear()
	this.Effect.Clear()
	this.Guest.Clear()
	this.Seat.Clear()
	this.Setting.Clear()
	this.Skill.Clear()
	this.Stage.Clear()
}

// Progress 取得進度值
func (this *Sheeter) Progress() float32 {
	return this.progress.Get()
}
