// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Skill Skill.xlsx#Skill
type Skill struct {
	EffectID []int32 `json:"EffectID"` // 效果編號列表
	Group int32 `json:"Group"` // 技能群組編號
	ID int32 `json:"ID"` // 技能編號
	Name string `json:"Name"` // 名稱
}

// SkillReader Skill.xlsx#Skill
type SkillReader struct {
	Data map[int32]*Skill // 資料列表
}

// FileName 取得檔名物件
func (this *SkillReader) FileName() FileName {
	return NewFileName("skill", ".json")
}

// FromData 讀取資料
func (this *SkillReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[int32]*Skill{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[int32]*Skill{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [skill : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *SkillReader) Clear() {
	this.Data = map[int32]*Skill{}
}

// Get 取得資料
func (this *SkillReader) Get(key int32) *Skill {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *SkillReader) Keys() (result []int32) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *SkillReader) Values() (result []*Skill) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *SkillReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *SkillReader) Count() int {
	return len(this.Data)
}
