// Code generated by sheeter. DO NOT EDIT.
// Sheeter: https://github.com/yinweli/Sheeter

package sheeter

import (
	"encoding/json"
	"fmt"
)

// Stage Stage.xlsx#Stage
type Stage struct {
	DeckID []int32 `json:"DeckID"` // 抽牌牌堆列表
	DropID []int32 `json:"DropID"` // 棄牌牌堆列表
	ExileID []int32 `json:"ExileID"` // 流放牌堆列表
	HandID []int32 `json:"HandID"` // 手牌列表
	ID int32 `json:"ID"` // 關卡編號
	Name string `json:"Name"` // 名稱
	PrefixSkillID []int32 `json:"PrefixSkillID"` // 前置技能列表
	WaitID []int32 `json:"WaitID"` // 排隊顧客列表
}

// StageReader Stage.xlsx#Stage
type StageReader struct {
	Data map[int32]*Stage // 資料列表
}

// FileName 取得檔名物件
func (this *StageReader) FileName() FileName {
	return NewFileName("stage", ".json")
}

// FromData 讀取資料
func (this *StageReader) FromData(data []byte, clear bool, progress *Progress) error {
	tmpl := map[int32]*Stage{}

	if err := json.Unmarshal(data, &tmpl); err != nil {
		return fmt.Errorf("from data: %w", err)
	} // if

	if clear || this.Data == nil {
		this.Data = map[int32]*Stage{}
	} // if

	task := progress.Reg()
	curr := 0
	total := len(tmpl)

	for k, v := range tmpl {
		if _, ok := this.Data[k]; ok {
			return fmt.Errorf("from data: key duplicate [stage : %v]", k)
		} // if

		this.Data[k] = v
		curr++
		progress.Set(task, curr, total)
	} // for

	return nil
}

// Clear 清除資料
func (this *StageReader) Clear() {
	this.Data = map[int32]*Stage{}
}

// Get 取得資料
func (this *StageReader) Get(key int32) *Stage {
	if result, ok := this.Data[key]; ok {
		return result
	} // if

	return nil
}

// Keys 取得索引列表
func (this *StageReader) Keys() (result []int32) {
	for itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Values 取得資料列表
func (this *StageReader) Values() (result []*Stage) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// ValuesAny 取得資料列表
func (this *StageReader) ValuesAny() (result []any) {
	for _, itor := range this.Data {
		result = append(result, itor)
	} // for

	return result
}

// Count 取得資料數量
func (this *StageReader) Count() int {
	return len(this.Data)
}
